[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "backtrack"
path = "src/backtrack/main.rs"

[[bin]]
name = "annealing"
path = "src/annealing/main.rs"

[dependencies]
itertools = "0.10.3"

