[package]
name = "grep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "skgrep"
path = "src/main.rs"

[dependencies]
colored = "2.0.0"
itertools = "0.10.3"
sudoku = { path = "../sudoku" }
